version: '3'

services:
    mysqlDB:
      image: mysql:5.7
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: superheroes
        MYSQL_DATABASE: superheroes
        MYSQL_USER: root
        MYSQL_PASSWORD: superheroes
      networks: 
        - superhero-bridge

    node-instance:
      container_name: superheroes
      image: sp/superheroes
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mysqlDB
      networks: 
        - superhero-bridge
      environment:
        - DB_NAME=superheroes
        - DB_USER=root
        - DB_TYPE=mysql
        - DB_PASSWORD=superheroes
        - DB_HOST=mysqlDB
        - DB_PORT=3306
        - ENV_PORT=3000 
networks: 
    superhero-bridge:
        driver: bridge
        