# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/X

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test

      # upload coverage!
      - run: npm run report-coverage

      - save_cache:
          paths:
            - .
          key: v1-dist{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}

  # The deploy job
  deploy:
      working_directory: ~/project
      docker:
          - image: circleci/node:9.11
      steps:
          - add_ssh_keys:
              fingerprints:
                  - "58:59:c9:9b:ad:c3:b6:b6:d0:bc:d5:6b:c2:82:01:c3"
          # Log the current branch
          - run:
              name: Show current branch
              command: echo ${CIRCLE_BRANCH}
          # Log the current branch
          - run:
              name: Show current place
              command: ls && pwd 
          # Log the current branch
          - run:
              name: Deploy Over SSH
              command: |
                npm run deploy

workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build
            # The deploy job will only run on the filtered branches and
            # require the build job to be successful before it starts
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - develop
                            - staging
                            - master