FROM mysql:5.6

ENV MYSQL_TCP_PORT=3306
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=superheroes
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=superheroes
ENV MYSQL_DATA_DIR=/var/lib/mysql
ENV MYSQL_RUN_DIR=/run/mysqld
ENV MYSQL_LOG_DIR=/var/log/mysql

EXPOSE 3306